/*        PIZZA DATASET ANALYSIS IN SQL     */

  use db_pizza;
/* CATEGORY WISE PIZZA SOLD */ 


      SELECT PIZZA_CATEGORY,SUM(QUANTITY) AS TOTAL_SOLD FROM TBL_PIZZA
      GROUP BY PIZZA_CATEGORY;

/* TOP TWO PIZZA CATEGORY */ 
     
      SELECT PIZZA_CATEGORY,SUM(QUANTITY) AS TOTAL_SOLD FROM TBL_PIZZA
      GROUP BY PIZZA_CATEGORY ORDER BY TOTAL_SOLD DESC LIMIT 2;

/* BOTTOM ONE PIZZA CATEGORY */
      
      SELECT PIZZA_CATEGORY,SUM(QUANTITY) AS TOTAL_SOLD FROM TBL_PIZZA
      GROUP BY PIZZA_CATEGORY ORDER BY TOTAL_SOLD  LIMIT 1;
      
/* PIZZA SIZE WISE PIZZA SOLD  */   

      SELECT PIZZA_SIZE,SUM(QUANTITY) AS TOTAL_PIZZA_SOLD  FROM TBL_PIZZA
      GROUP BY PIZZA_SIZE;
 
 /* TOP 2 PIZZA SOLD IN PIZZA SIZE */   

      SELECT PIZZA_SIZE,SUM(QUANTITY) AS TOTAL_PIZZA_SOLD  FROM TBL_PIZZA
      GROUP BY PIZZA_SIZE ORDER BY TOTAL_PIZZA_SOLD DESC LIMIT 2;


/* BOTTOM 2 PIZZA SOLD IN PIZZA SIZE */   

      SELECT PIZZA_SIZE,SUM(QUANTITY) AS TOTAL_PIZZA_SOLD  FROM TBL_PIZZA
      GROUP BY PIZZA_SIZE ORDER BY TOTAL_PIZZA_SOLD  LIMIT 2;
      
  
/* TOTAL REVENUE */   

      
    SELECT SUM(TOTAL_PRICE) AS TOTAL_REVENUE FROM TBL_PIZZA;
    
    
/* TOTAL REVENUE BY PIZZA_CATEGORY WISE */

      SELECT PIZZA_CATEGORY,SUM(TOTAL_PRICE) FROM TBL_PIZZA
      GROUP BY PIZZA_CATEGORY;

/* TOP 2  TOTAL REVENUE BY PIZZA_CATEGORY WISE */

      SELECT PIZZA_CATEGORY,SUM(TOTAL_PRICE) AS TOTAL_REVENUE FROM TBL_PIZZA
      GROUP BY PIZZA_CATEGORY ORDER BY TOTAL_REVENUE DESC LIMIT 2;
      
/* BOTTOM  2  TOTAL REVENUE BY PIZZA_CATEGORY WISE */

      SELECT PIZZA_CATEGORY,SUM(TOTAL_PRICE) AS TOTAL_REVENUE FROM TBL_PIZZA
      GROUP BY PIZZA_CATEGORY ORDER BY TOTAL_REVENUE  LIMIT 2;


/* TOTAL REVENUE BY PIZZA_SIZE WISE */

      SELECT PIZZA_SIZE,SUM(TOTAL_PRICE) FROM TBL_PIZZA
      GROUP BY PIZZA_SIZE;

/* TOP 2  TOTAL REVENUE BY PIZZA_SIZE WISE */

      SELECT PIZZA_SIZE,SUM(TOTAL_PRICE) AS TOTAL_REVENUE FROM TBL_PIZZA
      GROUP BY PIZZA_SIZE ORDER BY TOTAL_REVENUE DESC LIMIT 2;
      
/* BOTTOM  2  TOTAL REVENUE BY PIZZA_SIZE WISE */

      SELECT PIZZA_SIZE,SUM(TOTAL_PRICE) AS TOTAL_REVENUE FROM TBL_PIZZA
      GROUP BY PIZZA_SIZE ORDER BY TOTAL_REVENUE  LIMIT 2;
      
      
/* WHAT TOTAL NUMBER PIZZA SIZE AVAILABLE BY CATEGORY WISE */   
     
     SELECT PIZZA_CATEGORY,COUNT(DISTINCT(PIZZA_SIZE)) AS PIZZA_SIZE_TYPE FROM TBL_PIZZA
     GROUP BY PIZZA_CATEGORY;
  

SELECT * FROM TBL_PIZZA;

            

      
      