/*  BASIC LEVEL PIZZA DATA ANALYSIS           */

/* 	SHOW ALL DATABASE NAME   */

      SHOW  DATABASES;
   
   
/* USE DATABASE DB_PIZZA  */

       USE DB_PIZZA;   
   

/* SHOW ALL TABLE NAME PRESENT IN DB_PIZZA  */

       SHOW TABLES;   
     
/*  FETCH ALL RECORD WITH ALL COLUMNS IN TBL_PIZZA   */

        SELECT * FROM TBL_PIZZA;     
    
/* FIND NUMBER OF RECORD  */ 

       SELECT COUNT(*) AS TOTAL_RECORD FROM TBL_PIZZA;
   
/* FIND lAST PIZZA ID  --> PIZZA-ID AUTO INCREMENT AND PRIMARY KEY */ 
   
	   SELECT MAX(PIZZA_ID) FROM TBL_PIZZA;
 
/* FIND LAST PIZZA ORDER DATE */
    
       SELECT ORDER_DATE FROM TBL_PIZZA ORDER BY PIZZA_ID DESC LIMIT 1;

/* FIND  HOW MANY ORDER IN LAST DATE*/


        SELECT ORDER_DATE,COUNT(distinct(ORDER_ID)) AS NUMBER_OF_ORDER FROM TBL_PIZZA
        WHERE ORDER_DATE  =  (SELECT ORDER_DATE FROM TBL_PIZZA ORDER BY PIZZA_ID DESC LIMIT 1)
		GROUP BY ORDER_DATE;     
  
/* FIND NUMBER OF  CATEGOTY OF PIZZA  */ 

        SELECT COUNT(distinct(PIZZA_CATEGORY)) AS PIZZA_CATEGORY FROM TBL_PIZZA;
 
/* FIND NAME OF   PIZZA CATEGORY */ 
 
        SELECT DISTINCT(PIZZA_CATEGORY) FROM TBL_PIZZA;
      
/* FIND HOW MANY NUMBER OF PIZZA SIZE  */    
   
        SELECT count(distinct(PIZZA_SIZE)) AS TYPE_OF_PIZZA_SIZE FROM TBL_PIZZA;
      
/* FIND NAME OF PIZZA SIZE  */   
        
        SELECT distinct(PIZZA_SIZE) AS NAME_OF_PIZZA_SIZE FROM TBL_PIZZA;
        
/* PIZZA NAME */ 

       SELECT DISTINCT(PIZZA_NAME) AS PIZZA_NAME  FROM TBL_PIZZA;   


/* NUMBER OF PIZZA NAME */ 

       SELECT COUNT(DISTINCT(PIZZA_NAME)) AS PIZZA_NAME  FROM TBL_PIZZA;   

/* HOW MANY PIZZA SOLD UPTO DATE */ 

      SELECT SUM(QUANTITY) AS TOTAL_PIZZA_SOLD FROM TBL_PIZZA; 
   
/* Total pizza order */ 

      SELECT count(distinct(order_id))  AS TOTAL_PIZZA_order FROM TBL_PIZZA;    
      
     SELECT * FROM TBL_PIZZA;   



